# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'CS394 Vote Application' do
pod 'Firebase'
end

target 'CS394 Vote ApplicationTests' do

end

