# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'PopularSongsCompare' do
pod 'Firebase'
end

target 'PopularSongsCompareTests' do

end

